---
name: linting
on: [push]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.0"

      - name: Install poetry
        run: |
          pip install poetry==1.1.11
          poetry config virtualenvs.create false
      - name: Install dependencies
        run: poetry install

      - name: Run flake8
        run: flake8

      - name: Run black
        run: make black

      - name: Run mypy
        run: make mypy

      - name: Run isort
        run: make isort
